catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.24
  velite: ^0.3.1
  "@tanstack/react-router": ^1.170.15
  "@tanstack/router-plugin": ^1.168.18
  "@fontsource-variable/jetbrains-mono": ^5.2.8
packages:
  - "."
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
  sharp: true
