catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.24
  "@tanstack/react-router": ^1.170.15
  "@tanstack/router-plugin": ^1.168.18
  "@fontsource-variable/jetbrains-mono": ^5.2.8
  gray-matter: ^4.0.3
  void: ^0.9.3
packages:
  - "."

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
