catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.24
  void: ^0.9.3
  "@void/react": ^0.9.3
  "@void/md": ^0.9.3
  "@fontsource-variable/jetbrains-mono": ^5.2.8
packages:
  - "."
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: true
  sharp: true
  workerd: set this to true or false
