/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as BlogRouteImport } from "./routes/blog";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as BlogIndexRouteImport } from "./routes/blog/index";
import { Route as BlogTagsRouteImport } from "./routes/blog/tags";
import { Route as BlogSlugRouteImport } from "./routes/blog/$slug";
import { Route as BlogTagsIndexRouteImport } from "./routes/blog/tags/index";
import { Route as BlogTagsTagRouteImport } from "./routes/blog/tags/$tag";

const BlogRoute = BlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BlogRoute,
} as any);
const BlogTagsRoute = BlogTagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => BlogRoute,
} as any);
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => BlogRoute,
} as any);
const BlogTagsIndexRoute = BlogTagsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BlogTagsRoute,
} as any);
const BlogTagsTagRoute = BlogTagsTagRouteImport.update({
  id: "/$tag",
  path: "/$tag",
  getParentRoute: () => BlogTagsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/blog": typeof BlogRouteWithChildren;
  "/blog/$slug": typeof BlogSlugRoute;
  "/blog/tags": typeof BlogTagsRouteWithChildren;
  "/blog/": typeof BlogIndexRoute;
  "/blog/tags/$tag": typeof BlogTagsTagRoute;
  "/blog/tags/": typeof BlogTagsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/blog": typeof BlogIndexRoute;
  "/blog/tags/$tag": typeof BlogTagsTagRoute;
  "/blog/tags": typeof BlogTagsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/blog": typeof BlogRouteWithChildren;
  "/blog/$slug": typeof BlogSlugRoute;
  "/blog/tags": typeof BlogTagsRouteWithChildren;
  "/blog/": typeof BlogIndexRoute;
  "/blog/tags/$tag": typeof BlogTagsTagRoute;
  "/blog/tags/": typeof BlogTagsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/blog"
    | "/blog/$slug"
    | "/blog/tags"
    | "/blog/"
    | "/blog/tags/$tag"
    | "/blog/tags/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/blog/$slug" | "/blog" | "/blog/tags/$tag" | "/blog/tags";
  id:
    | "__root__"
    | "/"
    | "/blog"
    | "/blog/$slug"
    | "/blog/tags"
    | "/blog/"
    | "/blog/tags/$tag"
    | "/blog/tags/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogRoute: typeof BlogRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/": {
      id: "/blog/";
      path: "/";
      fullPath: "/blog/";
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof BlogRoute;
    };
    "/blog/tags": {
      id: "/blog/tags";
      path: "/tags";
      fullPath: "/blog/tags";
      preLoaderRoute: typeof BlogTagsRouteImport;
      parentRoute: typeof BlogRoute;
    };
    "/blog/$slug": {
      id: "/blog/$slug";
      path: "/$slug";
      fullPath: "/blog/$slug";
      preLoaderRoute: typeof BlogSlugRouteImport;
      parentRoute: typeof BlogRoute;
    };
    "/blog/tags/": {
      id: "/blog/tags/";
      path: "/";
      fullPath: "/blog/tags/";
      preLoaderRoute: typeof BlogTagsIndexRouteImport;
      parentRoute: typeof BlogTagsRoute;
    };
    "/blog/tags/$tag": {
      id: "/blog/tags/$tag";
      path: "/$tag";
      fullPath: "/blog/tags/$tag";
      preLoaderRoute: typeof BlogTagsTagRouteImport;
      parentRoute: typeof BlogTagsRoute;
    };
  }
}

interface BlogTagsRouteChildren {
  BlogTagsTagRoute: typeof BlogTagsTagRoute;
  BlogTagsIndexRoute: typeof BlogTagsIndexRoute;
}

const BlogTagsRouteChildren: BlogTagsRouteChildren = {
  BlogTagsTagRoute: BlogTagsTagRoute,
  BlogTagsIndexRoute: BlogTagsIndexRoute,
};

const BlogTagsRouteWithChildren = BlogTagsRoute._addFileChildren(BlogTagsRouteChildren);

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute;
  BlogTagsRoute: typeof BlogTagsRouteWithChildren;
  BlogIndexRoute: typeof BlogIndexRoute;
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogTagsRoute: BlogTagsRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
};

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
